DB_URL = "http://mistral.rdla.fr/api/"
ASSETS_URL = "http://assets.rdla.fr/"
FTP_URL = "ftp.rdla.fr"
FTP_USER = ENV['FTP_USER']
FTP_PASSWORD = ENV['FTP_PASSWORD']
FACEBOOK_LOGIN = ENV['FACEBOOK_LOGIN']
FACEBOOK_PASSWORD = ENV['FACEBOOK_PASSWORD']
